packer {
  required_plugins {
    proxmox = {
      version = "= 1.2.1"
      source  = "github.com/hashicorp/proxmox"
    }
  }
}


variable "proxmox_node" {
  type    = string
  default = ""
}

variable "proxmox_password" {
  type    = string
  default = ""
}

variable "proxmox_storage_format" {
  type    = string
  default = "raw"
}

variable "proxmox_storage_pool" {
  type    = string
  default = "local-lvm"
}

variable "proxmox_storage_pool_type" {
  type    = string
  default = "lvm-thin"
}

variable "proxmox_url" {
  type    = string
  default = ""
}

variable "proxmox_username" {
  type    = string
  default = "root@pam"
}

variable "template_description" {
  type    = string
  default = "Rocky Linux 9 Template"
}

variable "template_name" {
  type    = string
  default = "RockyLinux-9"
}

variable "version" {
  type    = string
  default = ""
}
#
source "proxmox-iso" "autogenerated_1" {
  boot_iso {
    type = "scsi"
    #iso_file = "local:iso/Rocky-9.5-x86_64-boot.iso"
    iso_url = "https://download.rockylinux.org/pub/rocky/9/isos/x86_64/Rocky-9.5-x86_64-boot.iso"
    iso_checksum = "file:https://download.rockylinux.org/pub/rocky/9/isos/x86_64/CHECKSUM"
    iso_download_pve = true
    iso_storage_pool = "local"

    unmount = true
  }
  boot_command = [
    "<up><tab><bs><bs><bs><bs><bs>text ip=dhcp",
    " inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/kickstart.cfg console=tty0",
    "<wait><enter>"
  ]
  boot_wait = "10s"
  cpu_type  = "host"
  cores     = 4
  disks {
    disk_size    = "8G"
    format       = "${var.proxmox_storage_format}"
    storage_pool = "${var.proxmox_storage_pool}"
    type         = "scsi"
  }
  http_directory           = "rocky9"
  insecure_skip_tls_verify = true
  memory                   = "4096"
  network_adapters {
    bridge = "vmbr0"
    model  = "virtio"
  }
  node                    = "${var.proxmox_node}"
  os                      = "l26"
  username                = "${var.proxmox_username}"
  password                = "${var.proxmox_password}"
  proxmox_url             = "${var.proxmox_url}"
  scsi_controller         = "virtio-scsi-single"
  ssh_password            = "packer"
  ssh_port                = 22
  ssh_timeout             = "30m"
  ssh_username            = "root"
  template_description    = "${var.template_description}"
  template_name           = "${var.template_name}"
  cloud_init              = true
  cloud_init_storage_pool = "${var.proxmox_storage_pool}"
  serials                 = ["socket", "/dev/ttyS0"]
  #vga {
  #  type   = "serial0"
  #  memory = 64
  #}
}

build {
  sources = ["source.proxmox-iso.autogenerated_1"]
  
  name = "proxmox-rl9"

  provisioner "shell" {
    inline = [
      "shred -u /etc/ssh/*_key /etc/ssh/*_key.pub", 
      "rm -f /var/run/utmp", 
      ">/var/log/lastlog", 
      ">/var/log/wtmp", 
      ">/var/log/btmp", 
      "rm -rf /tmp/* /var/tmp/*", 
      "unset HISTFILE; rm -rf /home/*/.*history /root/.*history", 
      "rm -f /root/*ks.cfg", 
      "rm -f /etc/ssh/sshd_config.d/allow-root-ssh.conf",
      "rm -f /var/lib/systemd/random-seed",
      "cat /dev/null > /etc/machine-id",
      "passwd -d root", 
      "passwd -l root"
    ]
  }
}
